# Generated by Django 4.2.7 on 2024-01-25 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialization', '0001_initial'),
        ('patient_vital', '0001_initial'),
        ('vital_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvital',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientvital',
            name='specialization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specialization.specialization'),
        ),
        migrations.AddField(
            model_name='patientvital',
            name='vital_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vital_master.vitalmaster'),
        ),
    ]
